version: '3'

services:
  backend:
    build: .
    container_name: backend
    depends_on:
      - pgsql
    volumes:
      - ./:/usr/src/app
    ports:
      - "${PORT_3000}:3000"
    environment:
      - TZ=Asia/Taipei
    command: npm run start:dev

  pgsql:
    image: postgres:12
    container_name: pgsql
    volumes:
      - ./data:/var/lib/postgresql/data
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      # - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Asia/Taipei
    ports:
      - "${PORT_5432}:5432"

